Algoritmo "soma"
//Fazer um programa para ler dois valores inteiros X e Y,
//e depois mostrar na tela o valor da soma destes números.
Var
// Seção de Declarações das variáveis
   valorX, valorY, soma : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         escreva ("Digite o valor de X: ")
         leia(valorX)
         escreva ("Digite o valor de Y: ")
         leia(valorY)
soma <- valorX + valorY
         escreva("SOMA = ", soma)

Fimalgoritmo